#!/usr/bin/env bash
# scripts/deploy-pages-branch.sh
#
# Regenerate the `gh-pages` branch from `prototype/overlay/` and push it.
# GitHub Pages (in "Deploy from a branch" mode) will then auto-deploy.
#
# This bypasses GitHub Actions entirely — useful when Actions can't allocate runners.
#
# Run from the repo root, on the prototype branch:
#   bash scripts/deploy-pages-branch.sh
#
# Idempotent: safe to run repeatedly. Each run rewrites gh-pages from scratch.

set -euo pipefail

# --- pre-flight checks ---

if [ ! -d .git ]; then
  echo "::error::Must be run from the repo root (no .git directory found)."
  exit 1
fi

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" != "prototype" ]; then
  echo "::error::Must be on the 'prototype' branch (currently on '$CURRENT_BRANCH')."
  echo "  Run: git checkout prototype && git pull"
  exit 1
fi

if [ ! -d overlay ]; then
  echo "::error::No overlay/ directory found in $(pwd)."
  exit 1
fi

if [ -z "$(ls -A overlay 2>/dev/null)" ]; then
  echo "::error::overlay/ directory is empty. Nothing to deploy."
  exit 1
fi

# Make sure git author is set correctly per repo convention
if [ "$(git config user.email)" != "rkw.kim22@gmail.com" ]; then
  echo "::warning::git user.email is '$(git config user.email)' — should be 'rkw.kim22@gmail.com' per BRANCHING.md."
  echo "  Setting it now."
  git config user.email "rkw.kim22@gmail.com"
  git config user.name "RKW-Kim"
fi

# --- save any uncommitted changes on prototype so we can restore them ---
STASHED=0
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "=== Stashing uncommitted changes on prototype ==="
  git stash 2>&1 | tail -2
  STASHED=1
fi

echo "=== Pre-flight OK ==="
echo "  Branch: $CURRENT_BRANCH"
echo "  Overlay files:"
ls -1 overlay/ | sed 's/^/    /'
echo ""

# --- snapshot prototype overlay/ contents ---

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"; if [ "$STASHED" = "1" ]; then git stash pop 2>&1 | tail -2 || true; fi' EXIT

echo "=== Snapshotting overlay/ to $TMP_DIR ==="
cp -r overlay/. "$TMP_DIR/"

# Add .nojekyll to disable Jekyll processing
# (ensures _shared.css, _shared.js, etc. are served by Pages)
touch "$TMP_DIR/.nojekyll"

# --- switch to gh-pages (or create orphan) ---

if git show-ref --verify --quiet refs/heads/gh-pages; then
  echo "=== gh-pages branch exists locally — checking it out ==="
  git checkout gh-pages 2>&1 | tail -3
else
  echo "=== gh-pages branch doesn't exist locally — fetching from origin ==="
  if git fetch origin gh-pages:gh-pages 2>&1 | tail -3; then
    git checkout gh-pages 2>&1 | tail -3
  else
    echo "=== gh-pages doesn't exist on origin either — creating orphan branch ==="
    git checkout --orphan gh-pages
  fi
fi

# --- wipe gh-pages tree completely and replace with snapshot ---

echo "=== Wiping gh-pages working tree (all files except .git) ==="
# Remove ALL files (tracked and untracked) except .git
find . -maxdepth 1 -mindepth 1 -not -name '.git' -exec rm -rf {} + 2>/dev/null || true
# Also clear any staged deletions
git rm -rf --cached . 2>&1 | tail -3 || true

echo "=== Restoring snapshot from $TMP_DIR ==="
cp -r "$TMP_DIR"/. ./
ls -la

# --- commit + push ---

echo "=== Staging changes ==="
git add -A

# Check if there are any changes to commit
if git diff --cached --quiet; then
  echo "=== No changes since last deploy — skipping commit/push ==="
  git checkout prototype 2>&1 | tail -3
  echo "=== Done (no changes) ==="
  exit 0
fi

COMMIT_MSG="chore(pages): regenerate gh-pages from prototype/overlay/

Files deployed:
$(ls -1 *.html 2>/dev/null | sed 's/^/  - /')

Generated by: scripts/deploy-pages-branch.sh
[Task ID: PAGES-DEPLOY]"

echo "=== Committing ==="
git commit -m "$COMMIT_MSG" 2>&1 | tail -3

echo "=== Pushing gh-pages to origin (force, because we rewrote history) ==="
git push origin gh-pages --force 2>&1 | tail -5

# --- switch back to prototype ---

echo "=== Switching back to prototype ==="
git checkout prototype 2>&1 | tail -3

echo ""
echo "=== Done ==="
echo "  GitHub Pages will auto-deploy in ~1-2 minutes."
echo "  Live URL: https://rkw-kim.github.io/world-21-suite/"
echo "  Overlay:  https://rkw-kim.github.io/world-21-suite/smile-v9.html"
