#!/usr/bin/env python3
"""
Regenerate brand.json from the overlay CSS — the single source of truth.

WHY THIS EXISTS
brand.json used to be hand-maintained and silently rotted: it claimed
--muted #8c8c8c while every page used #A1A1AA, carried five tokens no page
ever reads, and omitted seven the pages depend on. core/smile-mark.js fetches
this file and pushes its tokens onto document.documentElement as CSS custom
properties, so the drift was not cosmetic — it shipped wrong values to the DOM.

The fix is not a corrected file, it is removing the hand-editing. Extract the
tokens from the pages, write brand.json, and fail CI when the two disagree.

  python3 scripts/sync-brand-tokens.py           # write brand.json
  python3 scripts/sync-brand-tokens.py --check   # exit 1 if stale (for CI)
"""
import json, re, glob, sys, os, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OVERLAY = os.path.join(ROOT, 'overlay')
TARGET = os.path.join(ROOT, 'brand.json')

# token -> the descriptive key DESIGN.md uses. Everything not listed here is
# still emitted (so nothing is lost) but lands under its raw name.
ALIAS = {
    '--yellow': 'brand', '--hot': 'brand-hot', '--ink': 'canvas',
    '--bg': 'surface-sunken', '--border': 'hairline', '--line': 'hairline-soft',
    '--panel': 'panel', '--panel-2': 'panel-raised',
    '--fg': 'text-primary', '--paper': 'text-primary',
    '--muted': 'text-muted', '--meta': 'text-muted', '--faint': 'text-faint',
    '--up': 'market-up', '--down': 'market-down', '--sky': 'market-alt',
    '--live': 'signal-live', '--up-soft': 'market-up-soft',
    '--down-soft': 'market-down-soft',
}
# not colours — carried through so the file documents the whole system
# --sc is a PER-SEAT override in speaking.html (each seat defines its own), so a
# difference between pages is its entire purpose, not a conflict.
NON_COLOR = {'--fd', '--fm', '--fe', '--font-display', '--font-body',
             '--font-mono', '--safe-b', '--eo', '--tks', '--sc', '--bg-hex'}


def extract():
    files = sorted(glob.glob(os.path.join(OVERLAY, '*.html')))
    values = collections.defaultdict(collections.Counter)
    where = collections.defaultdict(set)
    for f in files:
        page = os.path.basename(f)
        for m in re.finditer(r'(--[a-z0-9-]+)\s*:\s*([^;}]+)', open(f).read()):
            tok, val = m.group(1), m.group(2).strip()
            if not re.fullmatch(r'(#[0-9a-fA-F]{3,8}|rgba?\([^)]*\))', val):
                continue
            values[tok][val.lower()] += 1
            where[tok].add(page)
    return values, where


def build():
    values, where = extract()
    colors, fonts, conflicts, meta = {}, {}, [], {}
    for tok, counter in sorted(values.items()):
        val, uses = counter.most_common(1)[0]
        pages = sorted(where[tok])
        # a token defined differently on different pages is a real conflict
        if len(counter) > 1 and tok not in NON_COLOR:
            conflicts.append({'token': tok,
                              'values': dict(counter),
                              'pages': pages})
        if tok in NON_COLOR:
            continue
        key = ALIAS.get(tok, tok.lstrip('-'))
        colors[key] = val
        meta[key] = {'token': tok, 'defined_in': pages, 'uses': uses}

    family = collections.Counter()
    for f in glob.glob(os.path.join(OVERLAY, '*.html')):
        for m in re.finditer(r"--(?:fd|font-display):\s*([^;}]+)", open(f).read()):
            family['display'] += 1
        for m in re.finditer(r"--(?:fm|font-mono):\s*([^;}]+)", open(f).read()):
            family['mono'] += 1

    return {
        'name': 'Smile',
        'wordmark': 'smile',
        'description': 'Broadcast overlay design tokens for smile.co.ke. '
                       'GENERATED by scripts/sync-brand-tokens.py from overlay/*.html '
                       '— do not hand-edit. Run --check in CI to catch drift.',
        'generated_from': 'overlay/*.html :root blocks',
        'colors': colors,
        'font_families': {
            'display': "'Space Grotesk', system-ui, sans-serif",
            'mono': "'IBM Plex Mono', ui-monospace, monospace",
            'body': "system-ui, -apple-system, 'Segoe UI', sans-serif",
        },
        'tokens': colors,          # what smile-mark.js consumes
        'provenance': meta,
        'conflicts': conflicts,
        'handles': {
            '@smileke': '@smileke',
            'smile.co.ke': 'smile.co.ke',
            '#SmileSquad': '#SmileSquad',
            "Kenya's all-in-one finance hub": "Kenya's all-in-one finance hub",
        },
    }


def main():
    data = build()
    out = json.dumps(data, indent=2) + '\n'
    if '--check' in sys.argv:
        cur = open(TARGET).read() if os.path.exists(TARGET) else ''
        if cur != out:
            print('FAIL brand.json is out of sync with overlay/*.html')
            print('      run: python3 scripts/sync-brand-tokens.py')
            if data['conflicts']:
                for c in data['conflicts']:
                    print(f"      conflict {c['token']}: {c['values']}")
            sys.exit(1)
        print('OK   brand.json matches overlay/*.html')
        return
    open(TARGET, 'w').write(out)
    print(f"wrote brand.json — {len(data['colors'])} colour tokens")
    if data['conflicts']:
        print('CONFLICTS (same token, different values across pages):')
        for c in data['conflicts']:
            print(f"  {c['token']}: {c['values']}  in {c['pages']}")


if __name__ == '__main__':
    main()
